apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: mqtt-broker
          image: eclipse-mosquitto
          ports:
            - containerPort: 1883
      restartPolicy: Always
      volumes: null
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
  labels:
    app: broker
spec:
  ports:
    - name: "mqtt"
      port: 1884
      targetPort: 1883
      protocol: TCP
  selector:
    app: broker
  type: NodePort
