apiVersion: v1
kind: Service
metadata:
  name: smart-pot-mqtt
  labels:
    app: smart-pot
spec:
  ports:
  - port: 1883
  selector:
    app: smart-pot
    tier: broker
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-pot-mqtt
  labels:
    app: smart-pot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-pot
      tier: broker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: smart-pot
        tier: broker
    spec:
      containers:
        - image: eclipse-mosquitto
          name: mqtt-broker
          ports:
          - containerPort: 1883
