apiVersion: v1
kind: Service
metadata:
  name: smart-pot-mysql
  labels:
    app: smart-pot
spec:
  ports:
  - port: 3306
  selector:
    app: smart-pot
    tier: mysql
  clusterIP: None
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-pot-mysql
  labels:
    app: smart-pot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-pot
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: smart-pot
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0.22
        name: mysql
        env:
          - name: MYSQL_DATABASE
            value: smart-pot
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_USER
            value: user
        ports:
        - containerPort: 3306
          name: mysql
