apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
data:
  root-password: cm9vdA==
  smart-pot-username: c21hcnQtcG90LXVzZXI=
  smart-pot-password: VGhlTW9zdCR0cjBuZ1Bhc3N3b3JkRm9yU21hcnRQb3RVc2VyMQ==
