apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sp-client
  name: sp-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sp-client
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sp-client
        tier: frontend
    spec:
      containers:
        - env:
            - name: CLOUD_API_URL
              value: http://0.0.0.0:8081/
          image: rborulchenko/smart-pot-client:latest
          name: smart-pot-client
          ports:
            - containerPort: 80
      restartPolicy: Always
      volumes: null
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sp-client
  name: sp-client-service
spec:
  ports:
    - name: "4200"
      port: 4200
      targetPort: 80
  selector:
    app: sp-client
    tier: frontend
  type: NodePort
