apiVersion: v1
kind: Service
metadata:
  labels:
    app: smart-pot
  name: smart-pot-core
spec:
  ports:
    - name: "8081"
      nodePort: 30081
      port: 8081
      targetPort: 8080
      protocol: TCP
  selector:
    app: smart-pot
    tier: backend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: smart-pot
  name: smart-pot-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-pot
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: smart-pot
        tier: backend
    spec:
      containers:
      - image: rborulchenko/smart-pot-core:latest
        name: smart-pot-core
        env:
          - name: MQTT_HOST
            value: smart-pot-mqtt
          - name: MQTT_PORT
            value: "1883"
          - name: MYSQL_URL
            value: jdbc:mysql://smart-pot-mysql:3306/smart-pot
        ports:
        - containerPort: 8080
